FROM php:fpm-alpine

# install gd
RUN apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
		openssl-dev \
		zlib-dev \
		# Memcached
		libmemcached-dev \
		cyrus-sasl-dev
RUN pecl install memcached redis \
	&& docker-php-ext-enable memcached redis \
	&& apk del .build-deps \
	# GD
	&& apk add --no-cache --update zlib-dev libpng-dev \
	&& docker-php-ext-install gd zip \
	&& apk del zlib-dev libpng-dev \
	&& rm -rf /tmp/* \

EXPOSE 9000

CMD ["php-fpm"]